# Generated by Django 3.0.8 on 2020-07-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200712_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitems',
            old_name='todo_list',
            new_name='todo',
        ),
    ]
